spring:
  application:
    name: account-service
  output.ansi.enabled: ALWAYS

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true


management.endpoints.web.exposure.include: '*'
management.metrics.distribution.percentiles-histogram.http.server.requests: true 
management.tracing.sampling.probability: 1.0
logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){red} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){blue} %clr(:){green} %clr(%m){faint}%n" # (3)

management:
  tracing:
    sampling:
      probability: 1.0
